In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [45]:
df=pd.read_csv('mushroom.csv')

## using label encoder
lst=[2,4,4,5,6,'a','b']
labelmaker=LabelEncoder()
labelmaker.fit(lst)
print("Classes are {}".format(labelmaker.classes_))
newLst=labelmaker.transform(lst)
print(newLst)
oldLst=labelmaker.inverse_transform(newLst)
print(oldLst)

Classes are ['2' '4' '5' '6' 'a' 'b']
[0 1 1 2 3 4 5]
['2' '4' '4' '5' '6' 'a' 'b']


In [68]:
print(df.shape)
df.head(5)

(8124, 23)


type cap_shape cap_surface cap_color bruises odor gill_attachment  \
0    p         x           s         n       t    p               f   
1    e         x           s         y       t    a               f   
2    e         b           s         w       t    l               f   
3    p         x           y         w       t    p               f   
4    e         x           s         g       f    n               f   

  gill_spacing gill_size gill_color   ...   stalk_surface_below_ring  \
0            c         n          k   ...                          s   
1            c         b          k   ...                          s   
2            c         b          n   ...                          s   
3            c         n          n   ...                          s   
4            w         b          k   ...                          s   

  stalk_color_above_ring stalk_color_below_ring veil_type veil_color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring_number ring_type spore_print_color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [70]:
le = LabelEncoder()
newDf=df.apply(le.fit_transform)
print(type(newDf))
print(le.classes_)
newDf.head(5)

<class 'pandas.core.frame.DataFrame'>
['d' 'g' 'l' 'm' 'p' 'u' 'w']


type  cap_shape  cap_surface  cap_color  bruises  odor  gill_attachment  \
0     1          5            2          4        1     6                1   
1     0          5            2          9        1     0                1   
2     0          0            2          8        1     3                1   
3     1          5            3          8        1     6                1   
4     0          5            2          3        0     5                1   

   gill_spacing  gill_size  gill_color   ...     stalk_surface_below_ring  \
0             0          1           4   ...                            2   
1             0          0           4   ...                            2   
2             0          0           5   ...                            2   
3             0          1           5   ...                            2   
4             1          0           4   ...                            2   

   stalk_color_above_ring  stalk_color_below_ring  veil_type  veil_color  \
0                       7                       7          0           2   
1                       7                       7          0           2   
2                       7                       7          0           2   
3                       7                       7          0           2   
4                       7                       7          0           2   

   ring_number  ring_type  spore_print_color  population  habitat  
0            1          4                  2           3        5  
1            1          4                  3           2        1  
2            1          4                  3           2        3  
3            1          4                  2           3        5  
4            1          0                  3           0        1  

[5 rows x 23 columns]

In [54]:
data=newDf.values
X = data[:,1:]
Y = data[:,0]
print(data)

[[1 5 2 ... 2 3 5]
 [0 5 2 ... 3 2 1]
 [0 0 2 ... 3 2 3]
 ...
 [0 2 2 ... 0 1 2]
 [1 3 3 ... 7 4 2]
 [0 5 2 ... 4 1 2]]


In [52]:
trainX,testX,trainY,testY=train_test_split(X,Y,test_size=0.2)
print(trainX.shape,trainY.shape)
print(testX.shape,testY.shape)

(6499, 22) (6499,)
(1625, 22) (1625,)


In [74]:
np.unique(trainY)

array([0, 1])

In [81]:
l=np.array([0,0,1,1,1,1,1,0,2,3,4,5,6,7,7,7])
np.sum(l==7)

3

## Naive Bayes Algo

In [83]:
def priorProbability(trainY,label):
    
    total_examples = trainY.shape[0]
    labelY_examples = np.sum(trainY==label)
    
    return labelY_examples/float(total_examples)

In [84]:
def conditionalProbability(trainX,trainY,feature,feature_val,label):
    
    X = trainX[trainY==label]     ## trainX havings rows with given label
    numerator = np.sum(X[:,feature]==feature_val)
    
    return numerator/float(X.shape[0])

In [86]:
# l=np.array([1,0,1,1,1,1,1,1,0,0])
# print(priorProbability(l,0))

In [87]:
def posteriorProbability(trainX,trainY,x,label):
    prior=priorProbability(trainY,label)
    likelihood=1
    for i in range(len(x)):
        likelihood*=conditionalProbability(trainX,trainY,i,x[i],label)
    posterior=likelihood*prior
    return posterior

In [95]:
def predictClass(trainX,trainY,x):
    prob = []
    for i in np.unique(trainY):
        prob.append(posteriorProbability(trainX,trainY,x,i))
    return np.argmax(prob)    

In [97]:
def accuracy(trainX,trainY,testX,testY):
    count=0
    m=testX.shape[0]
    for i in range(m):
        if testY[i]==predictClass(trainX,trainY,testX[i]):
            count+=1
    return count/m     

In [99]:
predictClass(trainX,trainY,testX[3])

1

In [100]:
accuracy(trainX,trainY,testX,testY)

0.9981538461538462

In [71]:
## using inverse_transform 
# oldDf=[]
# for i in range(data.shape[0]):
#     oldDf.append(le.inverse_transform(data[i]))
# oldDf=pd.DataFrame(oldDf)
# print(oldDf.head(3))